// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdxrtzthdxjwgrduevdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkeHJ0enRoZHhqd2dyZHVldmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTQ2NTgsImV4cCI6MjA3NDI3MDY1OH0.o5nqXNNlCGDHTSRjLMOqwLOlsqQtJoTLW0Am5gmmysU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});